"use client";
import { useEffect, useState } from "react";
import type { Hex } from "viem";
import { arcTestnet } from "viem/chains";
import { useConnection, usePublicClient, useWriteContract } from "wagmi";
import { useVerifiedWalletChain } from "@/hooks/useVerifiedWalletChain";
import { useWalletBalances } from "@/hooks/useWalletBalances";
import { erc20BalanceAbi } from "@/lib/abi/erc20";
import { formatAssetAmount, getAssetById, parseAssetAmount, SUPPORTED_ASSETS, type SupportedAssetId } from "@/lib/assets";
import { ARC_EXPLORER_URL } from "@/lib/config";
import { classifyWalletFailure } from "@/lib/walletSafety";
import { confirmThenRefresh } from "@/lib/confirmedTransaction";
import { buildXyloSwapRequest, createXyloQuote, exactApprovalRequired, isSwapQuoteFresh, minimumSwapOutput, oppositeAssetId, swapAmountForPercent, SWAP_SLIPPAGE_OPTIONS, XYLO_ROUTER, xyloRouterAbi, type SwapQuickPercent, type SwapQuote } from "@/lib/swap";
import { globalReviewChecks } from "@/lib/transactionReview";
import { TransactionSafetyReview } from "./TransactionSafetyReview";

type Props = { locale: "en" | "vi"; onBusyChange(busy: boolean): void; onConfirmed?(): void };
export function RealSwapFlow({ locale, onBusyChange, onConfirmed }: Props) {
  const vi = locale === "vi", connection = useConnection(), chain = useVerifiedWalletChain(), client = usePublicClient({ chainId: arcTestnet.id }), writer = useWriteContract(), balances = useWalletBalances(connection.address, chain.isArc);
  const [fromId, setFromId] = useState<SupportedAssetId>("usdc"), [amount, setAmount] = useState(""), [slippage, setSlippage] = useState<(typeof SWAP_SLIPPAGE_OPTIONS)[number]>(0.005), [quote, setQuote] = useState<SwapQuote>(), [reviewing, setReviewing] = useState(false), [pending, setPending] = useState<string>(), [error, setError] = useState<string>(), [quickFeedback, setQuickFeedback] = useState<string>(), [success, setSuccess] = useState<{ hash: Hex; quote: SwapQuote; received: bigint }>();
  const [reviewedAccount, setReviewedAccount] = useState<`0x${string}`>(), [approvalRequired, setApprovalRequired] = useState(false);
  useEffect(() => onBusyChange(Boolean(pending)), [onBusyChange, pending]);
  const from = getAssetById(fromId)!, to = getAssetById(oppositeAssetId(fromId))!, balance = balances.assets[fromId].data ?? 0n, parsed = parseAssetAmount(amount, from);
  const quickPercents = [25, 50, 75, 100] as const;
  function changeAmount(value: string) { setAmount(value); setQuote(undefined); setReviewing(false); setError(undefined); setQuickFeedback(undefined); }
  function chooseQuickAmount(percent: SwapQuickPercent) { const selected = swapAmountForPercent(balance, percent); changeAmount(selected > 0n ? formatAssetAmount(selected, from) : ""); if (selected === 0n) setQuickFeedback(vi ? "Số dư quá nhỏ cho tỷ lệ này." : "Balance too small for this percentage."); }
  function reset() { setAmount(""); setQuote(undefined); setReviewing(false); setError(undefined); setQuickFeedback(undefined); setSuccess(undefined); }
  async function review() {
    if (!connection.address || !client || !parsed) return setError(vi ? "Nhập số tiền hợp lệ." : "Enter a valid amount.");
    if (parsed > balance) return setError(vi ? "Số dư không đủ." : "Insufficient balance.");
    setPending(vi ? "Đang lấy báo giá trực tiếp từ XyloNet…" : "Loading a live XyloNet quote…"); setError(undefined); setQuote(undefined);
    try { if (!(await chain.verifyNow())) throw new Error("arc"); const [output, allowance] = await Promise.all([client.readContract({ address: XYLO_ROUTER, abi: xyloRouterAbi, functionName: "getAmountOut", args: [from.address, to.address, parsed] }), client.readContract({ address: from.address, abi: erc20BalanceAbi, functionName: "allowance", args: [connection.address, XYLO_ROUTER] })]); setQuote(createXyloQuote(from.id, to.id, parsed, output)); setApprovalRequired(allowance < parsed); setReviewedAccount(connection.address); setReviewing(true); }
    catch (caught) { setError(caught instanceof Error && caught.message === "arc" ? (vi ? "Cần kết nối Arc Testnet." : "Arc Testnet is required.") : (vi ? "Không lấy được báo giá XyloNet." : "Could not load a XyloNet quote.")); } finally { setPending(undefined); }
  }
  async function execute() {
    if (!connection.address || !client || !quote || pending) return;
    if (!reviewedAccount || connection.address.toLowerCase() !== reviewedAccount.toLowerCase()) { setReviewing(false); return setError(vi ? "Chi tiết giao dịch đã thay đổi. Vui lòng kiểm tra lại." : "Transaction details changed. Please review again."); }
    if (!isSwapQuoteFresh(quote.quotedAt)) { setQuote(undefined); setReviewing(false); return setError(vi ? "Báo giá đã hết hạn." : "Quote expired. Get a fresh quote."); }
    let submitted = false; setError(undefined);
    try {
      if (!(await chain.verifyNow())) throw new Error("arc");
      let freshBalance = await client.readContract({ address: from.address, abi: erc20BalanceAbi, functionName: "balanceOf", args: [connection.address] }); if (quote.amountIn > freshBalance) throw new Error("balance");
      const allowance = await client.readContract({ address: from.address, abi: erc20BalanceAbi, functionName: "allowance", args: [connection.address, XYLO_ROUTER] }); const approval = exactApprovalRequired(allowance, quote.amountIn);
      if (approval) { setPending(vi ? "Đang chờ approve đúng số lượng trong ví…" : "Waiting for exact token approval…"); await client.simulateContract({ address: from.address, abi: erc20BalanceAbi, functionName: "approve", args: [XYLO_ROUTER, approval], account: connection.address }); const approvalHash = await writer.writeContractAsync({ address: from.address, abi: erc20BalanceAbi, functionName: "approve", args: [XYLO_ROUTER, approval], account: connection.address, chainId: arcTestnet.id }); if ((await client.waitForTransactionReceipt({ hash: approvalHash })).status !== "success") throw new Error("approve"); }
      if (!isSwapQuoteFresh(quote.quotedAt)) { setQuote(undefined); setReviewing(false); return setError(vi ? "Approve xong nhưng báo giá đã hết hạn. Không gửi swap." : "Approval succeeded, but the quote expired. No swap was sent."); }
      if (!(await chain.verifyNow())) throw new Error("arc"); freshBalance = await client.readContract({ address: from.address, abi: erc20BalanceAbi, functionName: "balanceOf", args: [connection.address] }); if (quote.amountIn > freshBalance) throw new Error("balance");
      const freshOutput = await client.readContract({ address: XYLO_ROUTER, abi: xyloRouterAbi, functionName: "getAmountOut", args: [from.address, to.address, quote.amountIn] }); const request = buildXyloSwapRequest(quote, freshOutput, slippage, connection.address);
      setPending(vi ? "Đang chờ bạn xác nhận swap trong ví…" : "Waiting for swap confirmation in your wallet…"); const simulation = await client.simulateContract(request); const hash = await writer.writeContractAsync(simulation.request); submitted = true; setPending(vi ? "Đã gửi. Đang chờ Arc xác nhận…" : "Submitted. Waiting for Arc confirmation…"); const receipt = await client.waitForTransactionReceipt({ hash }); if (receipt.status !== "success") throw new Error("revert");
      await confirmThenRefresh({ receipt: Promise.resolve(receipt), onConfirmed: () => { setSuccess({ hash, quote, received: freshOutput }); setReviewing(false); }, refresh: async () => { await Promise.all([balances.usdc.refetch(), balances.eurc.refetch()]); onConfirmed?.(); } });
    } catch (caught) { if (caught instanceof Error && caught.message === "arc") return setError(vi ? "Cần kết nối Arc Testnet." : "Arc Testnet is required."); if (caught instanceof Error && caught.message === "balance") return setError(vi ? "Số dư vừa thay đổi và không còn đủ." : "Your balance changed and is no longer sufficient."); const kind = classifyWalletFailure(caught, submitted); setError(({ rejected: vi ? "Bạn đã từ chối yêu cầu trong ví." : "You rejected the wallet request.", "wrong-network": vi ? "Ví không còn ở Arc Testnet." : "Your wallet is no longer on Arc Testnet.", "insufficient-gas": vi ? "Không đủ USDC để trả gas trên Arc." : "Not enough USDC to pay Arc gas.", reverted: vi ? "Giao dịch bị revert." : "The transaction reverted.", "confirmation-unknown": vi ? "Trạng thái chưa rõ. Kiểm tra ArcScan." : "Confirmation is unclear. Check ArcScan.", rpc: vi ? "Ví hoặc RPC gặp lỗi." : "The wallet or RPC failed." } as const)[kind]); } finally { setPending(undefined); }
  }
  if (success) { const sold = getAssetById(success.quote.fromAssetId)!, bought = getAssetById(success.quote.toAssetId)!; return <div className="transaction-state"><span>✓</span><h3>{vi ? "Hoán đổi thành công" : "Swap confirmed"}</h3><p>{formatAssetAmount(success.quote.amountIn, sold)} {sold.symbol} → ≈ {formatAssetAmount(success.received, bought)} {bought.symbol}</p><a href={`${ARC_EXPLORER_URL}/tx/${success.hash}`} target="_blank" rel="noreferrer">ArcScan ↗</a><button type="button" className="standalone-action" onClick={reset}>{vi ? "Hoán đổi tiếp" : "Swap again"}</button></div>; }
  if (reviewing && quote) return <TransactionSafetyReview title={vi ? "Kiểm tra hoán đổi" : "Review Swap"} summary={vi ? "Kiểm tra báo giá và mức tối thiểu trước khi ví yêu cầu chữ ký." : "Review the quote and guaranteed minimum before the wallet requests signatures."} details={[{ label: vi ? "Bán" : "From", value: `${formatAssetAmount(quote.amountIn, from)} ${from.symbol}` }, { label: vi ? "Ước tính nhận" : "Current quote", value: `≈ ${formatAssetAmount(quote.amountOut, to)} ${to.symbol}` }, { label: vi ? "Tối thiểu nhận" : "Minimum received", value: `${formatAssetAmount(minimumSwapOutput(quote.amountOut, slippage), to)} ${to.symbol}` }, { label: vi ? "Tuyến" : "Route", value: "XyloNet StableSwap" }, { label: "Slippage", value: `${(slippage * 100).toFixed(1)}%` }, { label: vi ? "Mạng" : "Network", value: "Arc Testnet · 5042002" }]} checks={[...globalReviewChecks({ connected: connection.isConnected, account: connection.address, reviewedAccount, isArc: chain.isArc, amount: quote.amountIn, balance }), { code: "quote", status: isSwapQuoteFresh(quote.quotedAt) ? "verified" : "blocking", label: isSwapQuoteFresh(quote.quotedAt) ? (vi ? "Báo giá còn hiệu lực" : "Quote is current") : (vi ? "Báo giá đã hết hạn" : "Quote expired") }, { code: "approval", status: "info", label: approvalRequired ? (vi ? "Có thể cần hai xác nhận ví: approve đúng số lượng, sau đó swap" : "Two wallet confirmations may be required: exact approval, then swap") : (vi ? "Allowance hiện tại đủ; không cần approve mới" : "Current allowance is sufficient; no new approval expected") }]} walletNotice={vi ? "Ví của bạn vẫn thực hiện phê duyệt cuối cùng. Đầu ra ước tính có thể thay đổi; giao dịch chỉ đảm bảo mức tối thiểu hiển thị." : "Your wallet still performs final approval. Estimated output may change; the transaction only guarantees the displayed minimum."} onBack={() => { setReviewing(false); setQuote(undefined); }} onContinue={() => void execute()} continueDisabled={Boolean(pending)}>{pending && <p className="transaction-progress" role="status">{pending}</p>}{error && <p className="field-error" role="alert">{error}</p>}</TransactionSafetyReview>;
  return <form className="create-form wallet-flow" onSubmit={(event) => { event.preventDefault(); void review(); }}><label>{vi ? "Tài sản bán" : "Sell asset"}<select className="asset-selector" value={fromId} onChange={(event) => { setFromId(event.target.value as SupportedAssetId); reset(); }}>{SUPPORTED_ASSETS.map((asset) => <option key={asset.id} value={asset.id}>{asset.symbol} · {asset.name}</option>)}</select></label><label>{vi ? "Tài sản nhận" : "Buy asset"}<select className="asset-selector" value={to.id} disabled><option>{to.symbol} · {to.name}</option></select></label><label>{vi ? "Số lượng" : "Amount"}<div className="wallet-field-with-action amount"><input inputMode="decimal" value={amount} onChange={(event) => changeAmount(event.target.value)} placeholder="0.00"/><span>{from.symbol}</span></div><small>{vi ? "Khả dụng" : "Available"}: {formatAssetAmount(balance, from)} {from.symbol}</small></label><div className="swap-quick-amounts" aria-label={vi ? "Chọn nhanh số lượng" : "Quick amount selection"}>{quickPercents.map((percent) => { const selected = swapAmountForPercent(balance, percent); const active = selected > 0n && parsed === selected; const label = percent === 100 ? "MAX" : `${percent}%`; const aria = vi ? percent === 100 ? "Dùng toàn bộ số dư khả dụng" : `Dùng ${percent}% số dư khả dụng` : percent === 100 ? "Use maximum available balance" : `Use ${percent}% of available balance`; return <button key={percent} type="button" onClick={() => chooseQuickAmount(percent)} disabled={balance <= 0n} aria-label={aria} aria-pressed={active} className={active ? "active" : undefined}>{label}</button>; })}</div>{quickFeedback && <p className="swap-quick-feedback" role="status">{quickFeedback}</p>}<label>Slippage<select className="asset-selector" value={slippage} onChange={(event) => setSlippage(Number(event.target.value) as (typeof SWAP_SLIPPAGE_OPTIONS)[number])}>{SWAP_SLIPPAGE_OPTIONS.map((value) => <option key={value} value={value}>{(value * 100).toFixed(1)}%</option>)}</select></label><p className="wallet-notice">{vi ? "Swap trực tiếp qua XyloNet trên Arc; Makoto không giữ private key." : "Direct XyloNet swap on Arc; Makoto never holds your private key."}</p>{pending && <p className="transaction-progress" role="status">{pending}</p>}{error && <p className="field-error" role="alert">{error}</p>}{!chain.isArc && <p className="field-error">{vi ? "Cần kết nối Arc Testnet." : "Arc Testnet is required."}</p>}<div className="modal-actions"><button type="submit" className="primary-action" disabled={Boolean(pending) || !chain.isArc}>{vi ? "Lấy báo giá" : "Get quote"}</button></div></form>;
}
