"use client";
import { useEffect, useState } from "react";
import type { Hex } from "viem";
import { arcTestnet } from "viem/chains";
import { useConnection, usePublicClient, useWriteContract } from "wagmi";
import { useVerifiedWalletChain } from "@/hooks/useVerifiedWalletChain";
import { useWalletBalances } from "@/hooks/useWalletBalances";
import { erc20BalanceAbi } from "@/lib/abi/erc20";
import { formatAssetAmount, getAssetById, parseAssetAmount, SUPPORTED_ASSETS, type SupportedAssetId } from "@/lib/assets";
import { ARC_EXPLORER_URL } from "@/lib/config";
import { classifyWalletFailure } from "@/lib/walletSafety";
import { buildXyloSwapRequest, createXyloQuote, exactApprovalRequired, isSwapQuoteFresh, minimumSwapOutput, oppositeAssetId, SWAP_SLIPPAGE_OPTIONS, XYLO_ROUTER, xyloRouterAbi, type SwapQuote } from "@/lib/swap";

type Props = { locale: "en" | "vi"; onBusyChange(busy: boolean): void; onConfirmed?(): void };
export function RealSwapFlow({ locale, onBusyChange, onConfirmed }: Props) {
  const vi = locale === "vi", connection = useConnection(), chain = useVerifiedWalletChain(), client = usePublicClient({ chainId: arcTestnet.id }), writer = useWriteContract(), balances = useWalletBalances(connection.address, chain.isArc);
  const [fromId, setFromId] = useState<SupportedAssetId>("usdc"), [amount, setAmount] = useState(""), [slippage, setSlippage] = useState<(typeof SWAP_SLIPPAGE_OPTIONS)[number]>(0.005), [quote, setQuote] = useState<SwapQuote>(), [reviewing, setReviewing] = useState(false), [pending, setPending] = useState<string>(), [error, setError] = useState<string>(), [success, setSuccess] = useState<{ hash: Hex; quote: SwapQuote; received: bigint }>();
  useEffect(() => onBusyChange(Boolean(pending)), [onBusyChange, pending]);
  const from = getAssetById(fromId)!, to = getAssetById(oppositeAssetId(fromId))!, balance = balances.assets[fromId].data ?? 0n, parsed = parseAssetAmount(amount, from);
  function reset() { setAmount(""); setQuote(undefined); setReviewing(false); setError(undefined); setSuccess(undefined); }
  async function review() {
    if (!connection.address || !client || !parsed) return setError(vi ? "Nhập số tiền hợp lệ." : "Enter a valid amount.");
    if (parsed > balance) return setError(vi ? "Số dư không đủ." : "Insufficient balance.");
    setPending(vi ? "Đang lấy báo giá trực tiếp từ XyloNet…" : "Loading a live XyloNet quote…"); setError(undefined); setQuote(undefined);
    try { if (!(await chain.verifyNow())) throw new Error("arc"); const output = await client.readContract({ address: XYLO_ROUTER, abi: xyloRouterAbi, functionName: "getAmountOut", args: [from.address, to.address, parsed] }); setQuote(createXyloQuote(from.id, to.id, parsed, output)); setReviewing(true); }
    catch (caught) { setError(caught instanceof Error && caught.message === "arc" ? (vi ? "Cần kết nối Arc Testnet." : "Arc Testnet is required.") : (vi ? "Không lấy được báo giá XyloNet." : "Could not load a XyloNet quote.")); } finally { setPending(undefined); }
  }
  async function execute() {
    if (!connection.address || !client || !quote || pending) return;
    if (!isSwapQuoteFresh(quote.quotedAt)) { setQuote(undefined); setReviewing(false); return setError(vi ? "Báo giá đã hết hạn." : "Quote expired. Get a fresh quote."); }
    let submitted = false; setError(undefined);
    try {
      if (!(await chain.verifyNow())) throw new Error("arc");
      let freshBalance = await client.readContract({ address: from.address, abi: erc20BalanceAbi, functionName: "balanceOf", args: [connection.address] }); if (quote.amountIn > freshBalance) throw new Error("balance");
      const allowance = await client.readContract({ address: from.address, abi: erc20BalanceAbi, functionName: "allowance", args: [connection.address, XYLO_ROUTER] }); const approval = exactApprovalRequired(allowance, quote.amountIn);
      if (approval) { setPending(vi ? "Đang chờ approve đúng số lượng trong ví…" : "Waiting for exact token approval…"); await client.simulateContract({ address: from.address, abi: erc20BalanceAbi, functionName: "approve", args: [XYLO_ROUTER, approval], account: connection.address }); const approvalHash = await writer.writeContractAsync({ address: from.address, abi: erc20BalanceAbi, functionName: "approve", args: [XYLO_ROUTER, approval], account: connection.address, chainId: arcTestnet.id }); if ((await client.waitForTransactionReceipt({ hash: approvalHash })).status !== "success") throw new Error("approve"); }
      if (!isSwapQuoteFresh(quote.quotedAt)) { setQuote(undefined); setReviewing(false); return setError(vi ? "Approve xong nhưng báo giá đã hết hạn. Không gửi swap." : "Approval succeeded, but the quote expired. No swap was sent."); }
      if (!(await chain.verifyNow())) throw new Error("arc"); freshBalance = await client.readContract({ address: from.address, abi: erc20BalanceAbi, functionName: "balanceOf", args: [connection.address] }); if (quote.amountIn > freshBalance) throw new Error("balance");
      const freshOutput = await client.readContract({ address: XYLO_ROUTER, abi: xyloRouterAbi, functionName: "getAmountOut", args: [from.address, to.address, quote.amountIn] }); const request = buildXyloSwapRequest(quote, freshOutput, slippage, connection.address);
      setPending(vi ? "Đang chờ bạn xác nhận swap trong ví…" : "Waiting for swap confirmation in your wallet…"); const simulation = await client.simulateContract(request); const hash = await writer.writeContractAsync(simulation.request); submitted = true; setPending(vi ? "Đã gửi. Đang chờ Arc xác nhận…" : "Submitted. Waiting for Arc confirmation…"); const receipt = await client.waitForTransactionReceipt({ hash }); if (receipt.status !== "success") throw new Error("revert");
      await Promise.all([balances.usdc.refetch(), balances.eurc.refetch()]); onConfirmed?.(); setSuccess({ hash, quote, received: freshOutput }); setReviewing(false);
    } catch (caught) { if (caught instanceof Error && caught.message === "arc") return setError(vi ? "Cần kết nối Arc Testnet." : "Arc Testnet is required."); if (caught instanceof Error && caught.message === "balance") return setError(vi ? "Số dư vừa thay đổi và không còn đủ." : "Your balance changed and is no longer sufficient."); const kind = classifyWalletFailure(caught, submitted); setError(({ rejected: vi ? "Bạn đã từ chối yêu cầu trong ví." : "You rejected the wallet request.", "wrong-network": vi ? "Ví không còn ở Arc Testnet." : "Your wallet is no longer on Arc Testnet.", "insufficient-gas": vi ? "Không đủ USDC để trả gas trên Arc." : "Not enough USDC to pay Arc gas.", reverted: vi ? "Giao dịch bị revert." : "The transaction reverted.", "confirmation-unknown": vi ? "Trạng thái chưa rõ. Kiểm tra ArcScan." : "Confirmation is unclear. Check ArcScan.", rpc: vi ? "Ví hoặc RPC gặp lỗi." : "The wallet or RPC failed." } as const)[kind]); } finally { setPending(undefined); }
  }
  if (success) { const sold = getAssetById(success.quote.fromAssetId)!, bought = getAssetById(success.quote.toAssetId)!; return <div className="transaction-state"><span>✓</span><h3>{vi ? "Hoán đổi thành công" : "Swap confirmed"}</h3><p>{formatAssetAmount(success.quote.amountIn, sold)} {sold.symbol} → ≈ {formatAssetAmount(success.received, bought)} {bought.symbol}</p><a href={`${ARC_EXPLORER_URL}/tx/${success.hash}`} target="_blank" rel="noreferrer">ArcScan ↗</a><button type="button" className="standalone-action" onClick={reset}>{vi ? "Hoán đổi tiếp" : "Swap again"}</button></div>; }
  if (reviewing && quote) return <div className="wallet-flow"><h3>{vi ? "Kiểm tra hoán đổi" : "Review swap"}</h3><dl className="wallet-review"><div><dt>{vi ? "Bán" : "Sell"}</dt><dd>{formatAssetAmount(quote.amountIn, from)} {from.symbol}</dd></div><div><dt>{vi ? "Ước tính nhận" : "Estimated receive"}</dt><dd>≈ {formatAssetAmount(quote.amountOut, to)} {to.symbol}</dd></div><div><dt>{vi ? "Tối thiểu" : "Minimum receive"}</dt><dd>{formatAssetAmount(minimumSwapOutput(quote.amountOut, slippage), to)} {to.symbol}</dd></div><div><dt>Venue</dt><dd>XyloNet StableSwap</dd></div><div><dt>Slippage</dt><dd>{(slippage * 100).toFixed(1)}%</dd></div><div><dt>{vi ? "Mạng" : "Network"}</dt><dd>Arc Testnet · 5042002</dd></div></dl><p className="wallet-notice">{vi ? "Báo giá ngắn hạn, approve đúng số lượng, ví của bạn ký giao dịch." : "Short-lived quote, exact approval, and your wallet signs every transaction."}</p>{pending && <p className="transaction-progress" role="status">{pending}</p>}{error && <p className="field-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="secondary-action" onClick={() => { setReviewing(false); setQuote(undefined); }} disabled={Boolean(pending)}>{vi ? "Quay lại" : "Back"}</button><button type="button" className="primary-action" onClick={() => void execute()} disabled={Boolean(pending) || !chain.isArc}>{vi ? "Xác nhận trong ví" : "Confirm in wallet"}</button></div></div>;
  return <form className="create-form wallet-flow" onSubmit={(event) => { event.preventDefault(); void review(); }}><label>{vi ? "Tài sản bán" : "Sell asset"}<select className="asset-selector" value={fromId} onChange={(event) => { setFromId(event.target.value as SupportedAssetId); reset(); }}>{SUPPORTED_ASSETS.map((asset) => <option key={asset.id} value={asset.id}>{asset.symbol} · {asset.name}</option>)}</select></label><label>{vi ? "Tài sản nhận" : "Buy asset"}<select className="asset-selector" value={to.id} disabled><option>{to.symbol} · {to.name}</option></select></label><label>{vi ? "Số lượng" : "Amount"}<div className="wallet-field-with-action amount"><input inputMode="decimal" value={amount} onChange={(event) => { setAmount(event.target.value); setQuote(undefined); setError(undefined); }} placeholder="0.00"/><span>{from.symbol}</span><button type="button" onClick={() => setAmount(formatAssetAmount(balance, from))}>MAX</button></div><small>{vi ? "Khả dụng" : "Available"}: {formatAssetAmount(balance, from)} {from.symbol}</small></label><label>Slippage<select className="asset-selector" value={slippage} onChange={(event) => setSlippage(Number(event.target.value) as (typeof SWAP_SLIPPAGE_OPTIONS)[number])}>{SWAP_SLIPPAGE_OPTIONS.map((value) => <option key={value} value={value}>{(value * 100).toFixed(1)}%</option>)}</select></label><p className="wallet-notice">{vi ? "Swap trực tiếp qua XyloNet trên Arc; Makoto không giữ private key." : "Direct XyloNet swap on Arc; Makoto never holds your private key."}</p>{pending && <p className="transaction-progress" role="status">{pending}</p>}{error && <p className="field-error" role="alert">{error}</p>}{!chain.isArc && <p className="field-error">{vi ? "Cần kết nối Arc Testnet." : "Arc Testnet is required."}</p>}<div className="modal-actions"><button type="submit" className="primary-action" disabled={Boolean(pending) || !chain.isArc}>{vi ? "Lấy báo giá" : "Get quote"}</button></div></form>;
}
