"use client";

import { useState } from "react";
import { useConnection, usePublicClient, useWriteContract } from "wagmi";
import { arcTestnet } from "viem/chains";
import { erc20BalanceAbi } from "@/lib/abi/erc20";
import { EXPECTED_USDC_ADDRESS } from "@/lib/config";
import { formatUsdc, shortAddress } from "@/lib/format";
import { arcScanTransactionUrl, validateUsdcSend, type WalletActivity } from "@/lib/wallet";
import { usePreferences } from "@/hooks/usePreferences";
import { useVerifiedWalletChain } from "@/hooks/useVerifiedWalletChain";
import { WalletPanel } from "./WalletPanel";

export function SendFlow({ balance, onClose, onConfirmed }: { balance: bigint; onClose(): void; onConfirmed(activity: WalletActivity): void }) {
  const { locale } = usePreferences();
  const c = locale === "vi" ? { title:"Gửi USDC", recipient:"Địa chỉ nhận", amount:"Số tiền", next:"Kiểm tra", back:"Quay lại", confirm:"Xác nhận trong ví", review:"Kiểm tra giao dịch", token:"Tài sản", network:"Mạng", destination:"Người nhận", note:"Ví của bạn sẽ yêu cầu xác nhận rõ ràng. Makoto không giữ khóa riêng.", invalidAddress:"Nhập địa chỉ ví hợp lệ.", invalidAmount:"Nhập số tiền lớn hơn 0, tối đa 6 chữ số thập phân.", insufficient:"Số dư USDC không đủ.", pending:"Đang chờ xác nhận và biên nhận từ Arc…", success:"Đã gửi USDC", failed:"Không thể gửi. Giao dịch có thể đã bị từ chối hoặc RPC không phản hồi.", view:"Xem trên ArcScan" } : { title:"Send USDC", recipient:"Recipient address", amount:"Amount", next:"Review", back:"Back", confirm:"Confirm in wallet", review:"Review transaction", token:"Asset", network:"Network", destination:"To", note:"Your wallet will ask for explicit confirmation. Makoto never holds your private keys.", invalidAddress:"Enter a valid wallet address.", invalidAmount:"Enter an amount greater than 0 with at most 6 decimals.", insufficient:"Your USDC balance is too low.", pending:"Waiting for wallet confirmation and an Arc receipt…", success:"USDC sent", failed:"Send failed. The request may have been rejected or the RPC did not respond.", view:"View on ArcScan" };
  const [recipient, setRecipient] = useState(""); const [amount, setAmount] = useState(""); const [reviewing, setReviewing] = useState(false); const [error, setError] = useState<string>(); const [hash, setHash] = useState<`0x${string}`>(); const [pending, setPending] = useState(false);
  const connection = useConnection(); const chain = useVerifiedWalletChain(); const writer = useWriteContract(); const client = usePublicClient({ chainId: arcTestnet.id });
  const validated = validateUsdcSend(recipient, amount, balance);
  function review() { if ("error" in validated) { setError(validated.error === "address" ? c.invalidAddress : validated.error === "balance" ? c.insufficient : c.invalidAmount); return; } setError(undefined); setReviewing(true); }
  async function submit() { if ("error" in validated || !connection.address || !chain.isArc || !client) return; setPending(true); setError(undefined); try { const txHash = await writer.writeContractAsync({ address: EXPECTED_USDC_ADDRESS, abi: erc20BalanceAbi, functionName:"transfer", args:[validated.address, validated.amount], account:connection.address, chainId:arcTestnet.id }); await client.waitForTransactionReceipt({ hash:txHash }); setHash(txHash); onConfirmed({ hash:txHash, direction:"send", amount:validated.amount, counterparty:validated.address }); } catch { setError(c.failed); } finally { setPending(false); } }
  return <WalletPanel title={c.title} onClose={onClose}>{hash ? <div className="transaction-state"><span>✓</span><h3>{c.success}</h3><p>{formatUsdc("error" in validated ? 0n : validated.amount)} USDC → {"error" in validated ? "" : shortAddress(validated.address)}</p><a href={arcScanTransactionUrl(hash)} target="_blank" rel="noreferrer">{c.view} ↗</a></div> : reviewing && !("error" in validated) ? <div className="wallet-flow"><h3>{c.review}</h3><dl className="wallet-review"><div><dt>{c.token}</dt><dd>USDC</dd></div><div><dt>{c.amount}</dt><dd>{formatUsdc(validated.amount)} USDC</dd></div><div><dt>{c.destination}</dt><dd>{validated.address}</dd></div><div><dt>{c.network}</dt><dd>Arc Testnet</dd></div></dl><p className="wallet-notice">{c.note}</p>{!chain.isArc && <p className="field-error">Arc Testnet required.</p>}{error && <p className="field-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="secondary-action" onClick={() => setReviewing(false)} disabled={pending}>{c.back}</button><button type="button" className="primary-action" onClick={() => void submit()} disabled={pending || !chain.isArc}>{pending ? c.pending : c.confirm}</button></div></div> : <form className="create-form wallet-flow" onSubmit={(e) => { e.preventDefault(); review(); }}><label>{c.recipient}<input value={recipient} onChange={(e) => setRecipient(e.target.value)} placeholder="0x…" spellCheck={false} /></label><label>{c.amount}<div className="amount-input"><input inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="0.00" /><span>USDC</span></div><small>{formatUsdc(balance)} USDC</small></label>{error && <p className="field-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="secondary-action" onClick={onClose}>{c.back}</button><button type="submit" className="primary-action">{c.next}</button></div></form>}</WalletPanel>;
}
