"use client";

import Link from "next/link";
import { useState, type ReactNode } from "react";
import { useConnection } from "wagmi";
import { arcTestnet } from "viem/chains";
import { AppHeader } from "./AppHeader";
import { useOwnerJars } from "@/hooks/useOwnerJars";
import { usePreferences } from "@/hooks/usePreferences";
import { useVerifiedWalletChain } from "@/hooks/useVerifiedWalletChain";
import { SUPPORTED_ASSETS } from "@/lib/assets";
import { ARC_EXPLORER_URL } from "@/lib/config";
import { shortAddress } from "@/lib/format";
import { walletKindFromConnector } from "@/lib/onboarding";
import { deriveNetworkSafety, deriveOverallSecurityStatus, deriveSecurityAlerts, summarizeJarProtection, type ProtectionLoadState, type SecurityAlert, type SecurityOverallStatus } from "@/lib/securityCenter";
import styles from "./MakotoWallet.module.css";
import { AppLockSettings } from "./AppLockSettings";

export function SettingsPage() {
  const { locale, setLocale, theme, setTheme, resetPreferences } = usePreferences();
  const connection = useConnection();
  const chain = useVerifiedWalletChain();
  const canReadJars = connection.isConnected && chain.isArc;
  const ownerJars = useOwnerJars(canReadJars ? connection.address : undefined);
  const [copied, setCopied] = useState(false);
  const vi = locale === "vi";
  const network = deriveNetworkSafety(connection.isConnected, chain.isArc);
  const protectionState: ProtectionLoadState = !canReadJars ? "unavailable" : ownerJars.isLoading ? "loading" : ownerJars.error ? "error" : "ready";
  const summary = summarizeJarProtection(ownerJars.jars);
  const alerts = deriveSecurityAlerts({ network, protectionState, summary });
  const overall = deriveOverallSecurityStatus(network, protectionState, alerts);
  const walletKind = walletKindFromConnector(connection.connector?.id);
  const switching = ["waiting", "switching", "missing"].includes(chain.switchStatus);

  async function copyAddress() { if (!connection.address) return; await navigator.clipboard.writeText(connection.address); setCopied(true); window.setTimeout(() => setCopied(false), 1600); }

  return <main className={styles.page}><div className={styles.shell}>
    <AppHeader />
    <span id="security" className={styles.routeAnchor} />
    <span id="guardian" className={styles.routeAnchor} />
    <span id="help" className={styles.routeAnchor} />
    <section className={styles.settingsHero}><p>{vi ? "TRUNG TÂM BẢO MẬT" : "SECURITY CENTER"}</p><h1>{vi ? "Bảo mật ví" : "Wallet security"}</h1><span>{vi ? "Kiểm tra trạng thái ví, mạng, bảo vệ hũ tiết kiệm và cách Makoto xử lý dữ liệu của bạn." : "Review your wallet, network, savings protection, and how Makoto handles your data."}</span></section>
    <section className={`${styles.securityOverview} ${styles[`securityOverview_${overall}`]}`} aria-labelledby="security-status-title"><div><span className={styles.securityEyebrow}>{vi ? "TRẠNG THÁI TỔNG QUAN" : "OVERALL STATUS"}</span><h2 id="security-status-title">{statusLabel(overall, vi)}</h2><p>{statusCopy(overall, vi)}</p></div><span className={styles.securityStatusDot} aria-hidden="true" /></section>

    <div className={styles.settingsGrid}>
      <AppLockSettings />
      <SettingsCard title={vi ? "Ví đang kết nối" : "Connected wallet"}>{connection.isConnected && connection.address ? <><InfoRow label={vi ? "Địa chỉ" : "Address"} value={shortAddress(connection.address)} /><InfoRow label={vi ? "Loại ví" : "Wallet type"} value={walletKind === "embedded" ? (vi ? "Ví nhúng Email / Social" : "Embedded Email / Social wallet") : (vi ? "Ví bên ngoài" : "External wallet")} /><InfoRow label={vi ? "Nhà cung cấp" : "Provider"} value={connection.connector?.name ?? (vi ? "Không xác định" : "Unknown")} /><InfoRow label={vi ? "Mạng kết nối" : "Connected network"} value={network === "correct" ? "Arc Testnet" : (vi ? "Chưa xác minh" : "Unverified")} /><InfoRow label={vi ? "Mô hình ký" : "Signing model"} value={vi ? "Ví kiểm soát" : "Wallet controlled"} /><p className={styles.settingsMuted}>{walletKind === "embedded" ? (vi ? "Việc xác thực và hạ tầng ví được cung cấp qua Reown AppKit. Mã ứng dụng Makoto không lưu khóa riêng tư thô của bạn." : "Authentication and wallet infrastructure are provided through Reown AppKit. Makoto application code does not store your raw private key.") : (vi ? "Việc xác nhận và ký giao dịch được thực hiện trong ví bạn đang kết nối." : "Transaction approval and signing are handled by your connected wallet.")}</p><div className={styles.settingsActions}><button type="button" onClick={() => void copyAddress()}>{copied ? (vi ? "Đã sao chép" : "Copied") : (vi ? "Sao chép địa chỉ" : "Copy address")}</button><a href={`${ARC_EXPLORER_URL}/address/${connection.address}`} target="_blank" rel="noreferrer">{vi ? "Xem trên ArcScan" : "View on ArcScan"} ↗</a></div></> : <p className={styles.settingsMuted}>{vi ? "Kết nối ví từ thanh điều hướng để kiểm tra địa chỉ, loại ví và trạng thái bảo vệ." : "Connect from the header to review your address, wallet type, and protection status."}</p>}</SettingsCard>
      <SettingsCard title={vi ? "An toàn mạng" : "Network safety"}><InfoRow label={vi ? "Mạng yêu cầu" : "Required network"} value="Arc Testnet" /><InfoRow label="Chain ID" value={String(arcTestnet.id)} /><InfoRow label={vi ? "Token gas" : "Gas token"} value="USDC" /><InfoRow label={vi ? "Trạng thái" : "Status"} value={network === "correct" ? (vi ? "Đúng mạng ✓" : "Correct network ✓") : network === "wrong" ? (vi ? "Sai mạng" : "Wrong network") : (vi ? "Chưa kết nối" : "Disconnected")} />{network === "wrong" && <div className={styles.settingsActions}><button type="button" disabled={switching} onClick={() => void chain.switchToArc()}>{switching ? (vi ? "Đang chuyển…" : "Switching…") : (vi ? "Chuyển sang Arc Testnet" : "Switch to Arc Testnet")}</button></div>}{chain.switchMessage && network === "wrong" && <p className={styles.settingsMuted} role="status">{chain.switchMessage}</p>}<a className={styles.settingsLink} href={ARC_EXPLORER_URL} target="_blank" rel="noreferrer">ArcScan ↗</a></SettingsCard>
      <SettingsCard title={vi ? "Ký giao dịch & quyền lưu ký" : "Signing & custody"}><InfoRow label={vi ? "Ký giao dịch" : "Transaction signing"} value={vi ? "Ví kiểm soát" : "Wallet controlled"} /><p className={styles.settingsMuted}>{vi ? "Makoto chuẩn bị giao dịch, nhưng ví đang hoạt động phải xác nhận và ký các thao tác ghi." : "Makoto prepares transactions, but the active wallet must approve and sign write operations."}</p><InfoRow label={vi ? "Quyền lưu ký" : "Custody"} value={vi ? "Không lưu ký" : "Non-custodial"} /><p className={styles.settingsMuted}>{vi ? "Makoto không vận hành tài khoản lưu ký tiền của người dùng." : "Makoto does not operate a custodial account for user funds."}</p></SettingsCard>
      <SettingsCard title={vi ? "Dữ liệu & quyền riêng tư" : "Data & privacy"}><ul className={styles.settingsDisclosure}><li>{vi ? "Danh bạ và người nhận gần đây chỉ được lưu trong trình duyệt này." : "Contacts and recent recipients are stored only in this browser."}</li><li>{vi ? "Metadata PRIVATE được mã hóa cục bộ bằng khóa dẫn xuất từ chữ ký ví; địa chỉ, số dư và thời gian trên chuỗi vẫn công khai." : "PRIVATE metadata is encrypted locally with a key derived from your wallet signature; on-chain addresses, balances, and timing remain public."}</li><li>{vi ? "Arc Memo được ghi công khai và vĩnh viễn trên chuỗi. Không nhập dữ liệu cá nhân hoặc bí mật." : "Arc Memo is public and permanent on-chain. Never include personal or secret information."}</li></ul></SettingsCard>
      <SettingsCard title={vi ? "Bảo vệ Makoto Vault" : "Makoto Vault protection"} wide>{protectionState === "loading" ? <p className={styles.settingsMuted}>{vi ? "Đang đọc trạng thái hũ từ Arc Testnet…" : "Reading jar state from Arc Testnet…"}</p> : protectionState !== "ready" ? <p className={styles.settingsMuted}>{network === "wrong" ? (vi ? "Chuyển sang Arc Testnet để kiểm tra bảo vệ hũ." : "Switch to Arc Testnet to review jar protection.") : network === "disconnected" ? (vi ? "Kết nối ví để kiểm tra bảo vệ hũ." : "Connect a wallet to review jar protection.") : (vi ? "Không thể xác minh trạng thái hũ lúc này." : "Jar protection state could not be verified right now.")}</p> : <div className={styles.securityMetrics}><SecurityMetric label={vi ? "Hũ tiết kiệm" : "Savings jars"} value={String(summary.total)} /><SecurityMetric label="SAFE / SHIELDED" value={`${summary.safe} / ${summary.shielded}`} /><SecurityMetric label="PUBLIC / PRIVATE" value={`${summary.publicMetadata} / ${summary.privateMetadata}`} /><SecurityMetric label={vi ? "Có Guardian" : "Guardian protected"} value={`${summary.guardianProtected} / ${summary.total}`} /><SecurityMetric label={vi ? "Có ví khôi phục" : "Recovery configured"} value={`${summary.recoveryConfigured} / ${summary.total}`} /><SecurityMetric label={vi ? "Đóng băng / đang chờ" : "Frozen / pending"} value={`${summary.frozen} / ${summary.pendingOwnerRecovery + summary.pendingGuardianChange}`} /></div>}<Link className={styles.settingsLink} href="/savings">{vi ? "Quản lý hũ tiết kiệm" : "Manage savings jars"} →</Link></SettingsCard>
      <SettingsCard title={vi ? "Cảnh báo bảo mật" : "Security alerts"} wide><div className={styles.securityAlerts} aria-live="polite">{alerts.length ? alerts.map((alert) => <AlertRow key={alert.code} alert={alert} vi={vi} />) : <div className={`${styles.securityAlert} ${styles.securityAlert_info}`}><strong>{vi ? "Không có cảnh báo đang hoạt động" : "No active alerts"}</strong><span>{vi ? "Mạng và trạng thái bảo vệ hũ hiện đã được xác minh." : "Network and jar protection state are currently verified."}</span></div>}</div></SettingsCard>
      <SettingsCard title={vi ? "Xác minh biên nhận" : "Receipt verification"}><p className={styles.settingsMuted}>{vi ? "Makoto đối chiếu biên nhận giao dịch và nhật ký Arc cho các hoạt động được hỗ trợ. Việc này xác minh kết quả trên chuỗi, không đảm bảo mọi giao dịch đều an toàn." : "Makoto checks transaction receipts and Arc logs for supported actions. This verifies the on-chain result; it does not guarantee every transaction is safe."}</p><Link className={styles.settingsLink} href="/#activity">{vi ? "Xem hoạt động" : "Review activity"} →</Link></SettingsCard>
      <SettingsCard title={vi ? "Trạng thái kiểm toán & beta" : "Audit & beta status"}><ul className={styles.settingsDisclosure}><li>{vi ? "Makoto Wallet là bản Public Beta chỉ dành cho Arc Testnet và chưa sẵn sàng cho mainnet." : "Makoto Wallet is an Arc Testnet-only Public Beta and is not mainnet-ready."}</li><li>{vi ? "Makoto Wallet và Makoto Vault chưa được kiểm toán bảo mật chuyên nghiệp độc lập." : "Makoto Wallet and Makoto Vault have not undergone an independent professional security audit."}</li><li>{vi ? "Tài sản testnet không có giá trị tiền tệ thực tế dự kiến." : "Testnet assets have no intended real-world monetary value."}</li></ul></SettingsCard>
    </div>

    <section className={styles.settingsSectionHeading}><p>{vi ? "TÙY CHỈNH" : "PREFERENCES"}</p><h2>{vi ? "Giao diện & ứng dụng" : "Interface & app"}</h2></section>
    <div className={styles.settingsGrid}><SettingsCard title={vi ? "Giao diện" : "Appearance"}><ChoiceGroup label={vi ? "Chủ đề" : "Theme"} value={theme} onChange={setTheme} options={[["system", vi ? "Hệ thống" : "System"], ["light", vi ? "Sáng" : "Light"], ["dark", vi ? "Tối" : "Dark"]]} /></SettingsCard><SettingsCard title={vi ? "Ngôn ngữ" : "Language"}><ChoiceGroup label={vi ? "Ngôn ngữ hiển thị" : "Display language"} value={locale} onChange={setLocale} options={[["en", "English"], ["vi", "Tiếng Việt"]]} /></SettingsCard><SettingsCard title={vi ? "Tài sản hỗ trợ" : "Supported assets"} wide>{SUPPORTED_ASSETS.map((asset) => <div className={styles.settingsAsset} key={asset.id}><span><strong>{asset.symbol}</strong><small>{shortAddress(asset.address)}</small></span><a href={`${ARC_EXPLORER_URL}/address/${asset.address}`} target="_blank" rel="noreferrer">ArcScan ↗</a></div>)}</SettingsCard></div>
    <section className={styles.settingsReset}><div><strong>{vi ? "Đặt lại tùy chọn giao diện" : "Reset interface preferences"}</strong><p>{vi ? "Chỉ đặt lại ngôn ngữ và giao diện. Không ngắt kết nối ví hoặc thay đổi dữ liệu blockchain." : "Resets only language and theme. It does not disconnect your wallet or change blockchain data."}</p></div><button type="button" onClick={resetPreferences}>{vi ? "Đặt lại" : "Reset"}</button></section>
  </div></main>;
}

function statusLabel(status: SecurityOverallStatus, vi: boolean) { return ({ protected: vi ? "Được bảo vệ" : "Protected", review: vi ? "Nên kiểm tra" : "Review recommended", disconnected: vi ? "Chưa kết nối" : "Disconnected", unknown: vi ? "Chưa xác định" : "Unknown" })[status]; }
function statusCopy(status: SecurityOverallStatus, vi: boolean) { return ({ protected: vi ? "Các kiểm tra mạng và bảo vệ hiện có không phát hiện cảnh báo đang hoạt động." : "Available network and protection checks found no active alerts.", review: vi ? "Có trạng thái cần bạn xem lại bên dưới." : "One or more states need your review below.", disconnected: vi ? "Kết nối ví để Makoto có thể kiểm tra trạng thái bảo vệ." : "Connect a wallet so Makoto can check your protection state.", unknown: vi ? "Makoto chưa thể xác minh đầy đủ trạng thái bảo vệ lúc này." : "Makoto cannot fully verify your protection state right now." })[status]; }
function alertText(alert: SecurityAlert, vi: boolean): [string, string] { const n = alert.count ?? 0; return ({ disconnected: [vi ? "Chưa kết nối ví" : "Wallet disconnected", vi ? "Kết nối ví để chạy các kiểm tra bảo mật." : "Connect a wallet to run security checks."], "wrong-network": [vi ? "Sai mạng" : "Wrong network", vi ? "Chuyển sang Arc Testnet trước khi tiếp tục." : "Switch to Arc Testnet before continuing."], "protection-loading": [vi ? "Đang kiểm tra hũ" : "Checking jars", vi ? "Đang tải trạng thái bảo vệ từ Arc Testnet." : "Loading protection state from Arc Testnet."], "protection-unavailable": [vi ? "Không thể xác minh hũ" : "Jar state unavailable", vi ? "Trạng thái bảo vệ chưa thể được xác minh. Hãy thử lại sau." : "Protection state could not be verified. Try again shortly."], "frozen-jars": [vi ? `${n} hũ đang đóng băng` : `${n} frozen jar${n === 1 ? "" : "s"}`, vi ? "Kiểm tra trạng thái khôi phục trước khi thao tác." : "Review recovery status before taking action."], "pending-owner-recovery": [vi ? `${n} yêu cầu khôi phục chủ sở hữu đang chờ` : `${n} pending owner recover${n === 1 ? "y" : "ies"}`, vi ? "Khôi phục chủ sở hữu thay đổi quyền kiểm soát hũ, không chuyển USDC." : "Owner recovery changes jar control; it does not transfer USDC."], "pending-guardian-change": [vi ? `${n} thay đổi Guardian đang chờ` : `${n} pending Guardian change${n === 1 ? "" : "s"}`, vi ? "Xem lại địa chỉ và trạng thái phê duyệt." : "Review the address and approval state."], "shielded-without-guardian": [vi ? `${n} hũ SHIELDED chưa có Guardian` : `${n} SHIELDED jar${n === 1 ? "" : "s"} without a Guardian`, vi ? "Guardian là lớp bảo vệ tùy chọn nhưng được khuyến nghị cho SHIELDED." : "A Guardian is optional but recommended for SHIELDED jars."], "shielded-without-recovery": [vi ? `${n} hũ SHIELDED chưa có ví khôi phục` : `${n} SHIELDED jar${n === 1 ? "" : "s"} without a Recovery Wallet`, vi ? "Ví khôi phục là lớp bảo vệ tùy chọn nhưng được khuyến nghị cho SHIELDED." : "A Recovery Wallet is optional but recommended for SHIELDED jars."] } satisfies Record<SecurityAlert["code"], [string, string]>)[alert.code]; }
function AlertRow({ alert, vi }: { alert: SecurityAlert; vi: boolean }) { const [title, detail] = alertText(alert, vi); return <div className={`${styles.securityAlert} ${styles[`securityAlert_${alert.severity}`]}`}><strong>{title}</strong><span>{detail}</span></div>; }
function SecurityMetric({ label, value }: { label: string; value: string }) { return <div className={styles.securityMetric}><span>{label}</span><strong>{value}</strong></div>; }
function SettingsCard({ title, children, wide = false }: { title: string; children: ReactNode; wide?: boolean }) { return <section className={`${styles.settingsCard} ${wide ? styles.settingsWide : ""}`}><h2>{title}</h2>{children}</section>; }
function InfoRow({ label, value }: { label: string; value: string }) { return <div className={styles.settingsInfo}><span>{label}</span><strong>{value}</strong></div>; }
function ChoiceGroup<T extends string>({ label, value, onChange, options }: { label: string; value: T; onChange(value: T): void; options: readonly (readonly [T, string])[] }) { return <fieldset className={styles.settingsChoices}><legend>{label}</legend>{options.map(([option, text]) => <label key={option}><input type="radio" name={label} value={option} checked={value === option} onChange={() => onChange(option)} /><span>{text}</span></label>)}</fieldset>; }
