import { parseAbi } from "viem";

// Keep this definition in the same field order as PenguJarV3.Jar. The human-readable
// ABI is intentionally complete for every read, write, and event used by the app.
export const penguJarV3Abi = parseAbi([
  "struct Jar { address owner; uint256 balance; uint256 targetAmount; uint64 unlockTime; uint64 createdAt; bool closed; uint8 mode; uint8 privacyMode; uint256 withdrawalDelay; uint256 withdrawalReadyAt; bytes32 metadataCommitment; address guardian; bool frozen; uint256 freezeRecoveryReadyAt; address pendingGuardian; uint256 guardianChangeReadyAt; address recoveryWallet; bool guardianChangeRecoveryApproved; address pendingOwner; uint256 ownerRecoveryReadyAt; bool guardianApprovedOwnerRecovery; string name; }",
  "function createJar(string name, uint256 targetAmount, uint64 unlockTime, uint256 initialDeposit) returns (uint256 jarId)",
  "function createShieldedJar(string name, uint256 targetAmount, uint64 unlockTime, uint256 initialDeposit, uint256 withdrawalDelay) returns (uint256 jarId)",
  "function createGuardianShieldedJar(string name, uint256 targetAmount, uint64 unlockTime, uint256 initialDeposit, uint256 withdrawalDelay, address guardian, address recoveryWallet) returns (uint256 jarId)",
  "function createPrivateJar(bytes32 metadataCommitment, uint64 unlockTime, uint256 initialDeposit) returns (uint256 jarId)",
  "function createPrivateShieldedJar(bytes32 metadataCommitment, uint64 unlockTime, uint256 initialDeposit, uint256 withdrawalDelay) returns (uint256 jarId)",
  "function createPrivateGuardianShieldedJar(bytes32 metadataCommitment, uint64 unlockTime, uint256 initialDeposit, uint256 withdrawalDelay, address guardian, address recoveryWallet) returns (uint256 jarId)",
  "function depositToJar(uint256 jarId, uint256 amount)",
  "function contributeToJar(uint256 jarId, uint256 amount)",
  "function requestWithdrawal(uint256 jarId)",
  "function cancelWithdrawalRequest(uint256 jarId)",
  "function withdrawJar(uint256 jarId)",
  "function freezeWithdrawal(uint256 jarId)",
  "function unfreezeJar(uint256 jarId)",
  "function requestGuardianChange(uint256 jarId, address newGuardian)",
  "function approveGuardianChange(uint256 jarId)",
  "function cancelGuardianChange(uint256 jarId)",
  "function executeGuardianChange(uint256 jarId)",
  "function requestOwnerRecovery(uint256 jarId, address newOwner)",
  "function approveOwnerRecovery(uint256 jarId)",
  "function executeOwnerRecovery(uint256 jarId)",
  "function getJar(uint256 jarId) view returns (Jar)",
  "function getOwnerJarIds(address owner) view returns (uint256[])",
  "function getContribution(uint256 jarId, address contributor) view returns (uint256)",
  "function getTotalContributed(uint256 jarId) view returns (uint256)",
  "function USDC() view returns (address)",
  "event JarCreated(uint256 indexed jarId, address indexed owner, string name, uint256 targetAmount, uint256 unlockTime)",
  "event JarSecurityConfigured(uint256 indexed jarId, uint8 mode, uint256 withdrawalDelay)",
  "event JarPrivacyConfigured(uint256 indexed jarId, uint8 privacyMode, bytes32 metadataCommitment)",
  "event JarDeposited(uint256 indexed jarId, address indexed from, uint256 amount, uint256 newBalance)",
  "event JarWithdrawn(uint256 indexed jarId, address indexed owner, uint256 amount)",
  "event JarContributed(uint256 indexed jarId, address indexed contributor, uint256 amount, uint256 contributorTotal, uint256 totalContributed, uint256 newBalance)",
  "event WithdrawalRequested(uint256 indexed jarId, address indexed owner, uint256 requestedAt, uint256 readyAt)",
  "event WithdrawalRequestCancelled(uint256 indexed jarId, address indexed owner)",
  "event WithdrawalFrozen(uint256 indexed jarId, address indexed guardian, uint256 recoveryReadyAt)",
  "event JarUnfrozen(uint256 indexed jarId, address indexed owner)",
  "event GuardianChangeRequested(uint256 indexed jarId, address indexed currentGuardian, address indexed newGuardian, uint256 readyAt)",
  "event GuardianChangeCancelled(uint256 indexed jarId, address indexed guardian)",
  "event GuardianChanged(uint256 indexed jarId, address indexed oldGuardian, address indexed newGuardian)",
  "event GuardianChangeApproved(uint256 indexed jarId, address indexed recoveryWallet)",
  "event OwnerRecoveryRequested(uint256 indexed jarId, address indexed recoveryWallet, address indexed newOwner, uint256 readyAt)",
  "event OwnerRecoveryApproved(uint256 indexed jarId, address indexed guardian)",
  "event OwnerRecovered(uint256 indexed jarId, address indexed oldOwner, address indexed newOwner)",
]);
