export const penguJarV2Abi = [
  {
    type: "event",
    name: "JarWithdrawn",
    anonymous: false,
    inputs: [
      { indexed: true, name: "jarId", type: "uint256" },
      { indexed: true, name: "owner", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "JarContributed",
    anonymous: false,
    inputs: [
      { indexed: true, name: "jarId", type: "uint256" },
      { indexed: true, name: "contributor", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "contributorTotal", type: "uint256" },
      { indexed: false, name: "totalContributed", type: "uint256" },
      { indexed: false, name: "newBalance", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "JarDeposited",
    anonymous: false,
    inputs: [
      { indexed: true, name: "jarId", type: "uint256" },
      { indexed: true, name: "from", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "newBalance", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "JarCreated",
    anonymous: false,
    inputs: [
      { indexed: true, name: "jarId", type: "uint256" },
      { indexed: true, name: "owner", type: "address" },
      { indexed: false, name: "name", type: "string" },
      { indexed: false, name: "targetAmount", type: "uint256" },
      { indexed: false, name: "unlockTime", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "createJar",
    stateMutability: "nonpayable",
    inputs: [
      { name: "name", type: "string", internalType: "string" },
      { name: "targetAmount", type: "uint256", internalType: "uint256" },
      { name: "unlockTime", type: "uint64", internalType: "uint64" },
      { name: "initialDeposit", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "jarId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "function",
    name: "depositToJar",
    stateMutability: "nonpayable",
    inputs: [
      { name: "jarId", type: "uint256", internalType: "uint256" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "contributeToJar",
    stateMutability: "nonpayable",
    inputs: [
      { name: "jarId", type: "uint256", internalType: "uint256" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "withdrawJar",
    stateMutability: "nonpayable",
    inputs: [{ name: "jarId", type: "uint256", internalType: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "USDC",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
  },
  {
    type: "function",
    name: "getOwnerJarIds",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
  },
  {
    type: "function",
    name: "getJar",
    stateMutability: "view",
    inputs: [{ name: "jarId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct PenguJarV2.Jar",
        components: [
          { name: "owner", type: "address", internalType: "address" },
          { name: "balance", type: "uint256", internalType: "uint256" },
          { name: "targetAmount", type: "uint256", internalType: "uint256" },
          { name: "unlockTime", type: "uint64", internalType: "uint64" },
          { name: "createdAt", type: "uint64", internalType: "uint64" },
          { name: "closed", type: "bool", internalType: "bool" },
          { name: "name", type: "string", internalType: "string" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getContribution",
    stateMutability: "view",
    inputs: [
      { name: "jarId", type: "uint256", internalType: "uint256" },
      { name: "contributor", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "function",
    name: "getTotalContributed",
    stateMutability: "view",
    inputs: [{ name: "jarId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  },
] as const;
