import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { webcrypto } from "node:crypto";
import { APP_LOCK_SIGNAL_KEY, APP_LOCK_STORAGE_KEY, clearMakotoConvenienceData, cooldownDuration, createAppLockConfig, inactivityExpired, isValidPin, isWeakPin, parseAppLockConfig, pinsMatch, recordFailedAttempt, resetFailedAttempts, verifyAppLockPin } from "./appLock.ts";
import { appLockRecommendation } from "./securityCenter.ts";

const cryptoApi = webcrypto as unknown as Crypto;
test("PIN validation requires six numeric digits and detects weak forms", () => { assert.equal(isValidPin("123456"), true); assert.equal(isValidPin("12345"), false); assert.equal(isValidPin("1234567"), false); assert.equal(isValidPin("12a456"), false); assert.equal(pinsMatch("246810", "246810"), true); assert.equal(pinsMatch("246810", "246811"), false); assert.equal(isWeakPin("000000"), true); assert.equal(isWeakPin("111111"), true); assert.equal(isWeakPin("123456"), true); assert.equal(isWeakPin("654321"), true); assert.equal(isWeakPin("246810"), false); });
test("PBKDF2 stores no raw PIN, verifies correctly, and PIN change creates a new salt", async () => { const first = await createAppLockConfig("246810", 300_000, cryptoApi); const second = await createAppLockConfig("135790", 300_000, cryptoApi); assert.notEqual(first.salt, second.salt); assert.notEqual(first.verifier, second.verifier); assert.equal(JSON.stringify(first).includes("246810"), false); assert.equal(await verifyAppLockPin("246810", first, cryptoApi), true); assert.equal(await verifyAppLockPin("246811", first, cryptoApi), false); assert.deepEqual(parseAppLockConfig(JSON.stringify(first)), first); });
test("manual/reload/inactivity state and cooldown helpers are deterministic", async () => { const config = await createAppLockConfig("246810", 60_000, cryptoApi); assert.ok(parseAppLockConfig(JSON.stringify(config))); assert.equal(inactivityExpired(1_000, 60_000, 60_999), false); assert.equal(inactivityExpired(1_000, 60_000, 61_000), true); assert.equal(inactivityExpired(1_000, 0, 999_999), false); let failed = config; for (let count = 0; count < 5; count += 1) failed = recordFailedAttempt(failed, 1_000); assert.equal(failed.cooldownUntil, 31_000); assert.equal(failed.failedAttempts, 0); assert.equal(cooldownDuration(99), 900_000); assert.deepEqual({ failedAttempts: resetFailedAttempts(failed).failedAttempts, cooldownUntil: resetFailedAttempts(failed).cooldownUntil }, { failedAttempts: 0, cooldownUntil: 0 }); });
test("reset clears only selected Makoto convenience data and preserves PRIVATE metadata", () => { const storage = new MemoryStorage({ [APP_LOCK_STORAGE_KEY]: "lock", [APP_LOCK_SIGNAL_KEY]: "signal", "makoto-wallet:contacts:v1:a": "contacts", "makoto-wallet:recent-recipients:v1:a": "recents", "makoto-wallet:activity:v3:a": "activity", "pengujar:v3:private-metadata:v1": "encrypted", "reown:session": "wallet" }); clearMakotoConvenienceData(storage); assert.equal(storage.getItem(APP_LOCK_STORAGE_KEY), null); assert.equal(storage.getItem("makoto-wallet:contacts:v1:a"), null); assert.equal(storage.getItem("pengujar:v3:private-metadata:v1"), "encrypted"); assert.equal(storage.getItem("reown:session"), "wallet"); });
test("provider uses storage synchronization without broadcasting PIN and gate hides application content", () => { const provider = readFileSync(new URL("../hooks/useAppLock.tsx", import.meta.url), "utf8"); const gate = readFileSync(new URL("../components/AppLockGate.tsx", import.meta.url), "utf8"); assert.match(provider, /StorageEvent/); assert.match(provider, /APP_LOCK_SIGNAL_KEY/); assert.doesNotMatch(provider, /JSON\.stringify\(\{[^}]*pin/i); assert.match(gate, /if \(!appLock\.locked\) return children/); assert.match(gate, /app-lock-screen/); });
test("Security Center treats disabled lock as optional attention, never wallet compromise", () => { assert.deepEqual(appLockRecommendation("enabled"), { severity: "info", label: "Local App Lock enabled" }); assert.deepEqual(appLockRecommendation("disabled"), { severity: "attention", label: "Optional App Lock is disabled" }); assert.doesNotMatch(appLockRecommendation("disabled").label, /compromised/i); });

class MemoryStorage {
  private data = new Map<string, string>(); constructor(initial: Record<string, string>) { for (const entry of Object.entries(initial)) this.data.set(...entry); }
  get length() { return this.data.size; } key(index: number) { return [...this.data.keys()][index] ?? null; } getItem(key: string) { return this.data.get(key) ?? null; } setItem(key: string, value: string) { this.data.set(key, value); } removeItem(key: string) { this.data.delete(key); }
}
